# Generated by Django 5.0.6 on 2024-07-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_goods_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
