# Generated by Django 5.0.6 on 2024-07-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_ammount_goods_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
