# Generated by Django 5.0.6 on 2024-07-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_category_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
